package com.rillsoft.stackpoadmin.domain;

import java.util.ArrayList;
import java.util.List;

public class ResourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public ResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andResource_nameIsNull() {
            addCriterion("resource_name is null");
            return (Criteria) this;
        }

        public Criteria andResource_nameIsNotNull() {
            addCriterion("resource_name is not null");
            return (Criteria) this;
        }

        public Criteria andResource_nameEqualTo(String value) {
            addCriterion("resource_name =", value, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameNotEqualTo(String value) {
            addCriterion("resource_name <>", value, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameGreaterThan(String value) {
            addCriterion("resource_name >", value, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameGreaterThanOrEqualTo(String value) {
            addCriterion("resource_name >=", value, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameLessThan(String value) {
            addCriterion("resource_name <", value, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameLessThanOrEqualTo(String value) {
            addCriterion("resource_name <=", value, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameLike(String value) {
            addCriterion("resource_name like", value, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameNotLike(String value) {
            addCriterion("resource_name not like", value, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameIn(List<String> values) {
            addCriterion("resource_name in", values, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameNotIn(List<String> values) {
            addCriterion("resource_name not in", values, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameBetween(String value1, String value2) {
            addCriterion("resource_name between", value1, value2, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_nameNotBetween(String value1, String value2) {
            addCriterion("resource_name not between", value1, value2, "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_descIsNull() {
            addCriterion("resource_desc is null");
            return (Criteria) this;
        }

        public Criteria andResource_descIsNotNull() {
            addCriterion("resource_desc is not null");
            return (Criteria) this;
        }

        public Criteria andResource_descEqualTo(String value) {
            addCriterion("resource_desc =", value, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descNotEqualTo(String value) {
            addCriterion("resource_desc <>", value, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descGreaterThan(String value) {
            addCriterion("resource_desc >", value, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descGreaterThanOrEqualTo(String value) {
            addCriterion("resource_desc >=", value, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descLessThan(String value) {
            addCriterion("resource_desc <", value, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descLessThanOrEqualTo(String value) {
            addCriterion("resource_desc <=", value, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descLike(String value) {
            addCriterion("resource_desc like", value, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descNotLike(String value) {
            addCriterion("resource_desc not like", value, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descIn(List<String> values) {
            addCriterion("resource_desc in", values, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descNotIn(List<String> values) {
            addCriterion("resource_desc not in", values, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descBetween(String value1, String value2) {
            addCriterion("resource_desc between", value1, value2, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_descNotBetween(String value1, String value2) {
            addCriterion("resource_desc not between", value1, value2, "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_typeIsNull() {
            addCriterion("resource_type is null");
            return (Criteria) this;
        }

        public Criteria andResource_typeIsNotNull() {
            addCriterion("resource_type is not null");
            return (Criteria) this;
        }

        public Criteria andResource_typeEqualTo(String value) {
            addCriterion("resource_type =", value, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeNotEqualTo(String value) {
            addCriterion("resource_type <>", value, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeGreaterThan(String value) {
            addCriterion("resource_type >", value, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeGreaterThanOrEqualTo(String value) {
            addCriterion("resource_type >=", value, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeLessThan(String value) {
            addCriterion("resource_type <", value, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeLessThanOrEqualTo(String value) {
            addCriterion("resource_type <=", value, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeLike(String value) {
            addCriterion("resource_type like", value, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeNotLike(String value) {
            addCriterion("resource_type not like", value, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeIn(List<String> values) {
            addCriterion("resource_type in", values, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeNotIn(List<String> values) {
            addCriterion("resource_type not in", values, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeBetween(String value1, String value2) {
            addCriterion("resource_type between", value1, value2, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_typeNotBetween(String value1, String value2) {
            addCriterion("resource_type not between", value1, value2, "resource_type");
            return (Criteria) this;
        }

        public Criteria andResource_statusIsNull() {
            addCriterion("resource_status is null");
            return (Criteria) this;
        }

        public Criteria andResource_statusIsNotNull() {
            addCriterion("resource_status is not null");
            return (Criteria) this;
        }

        public Criteria andResource_statusEqualTo(Integer value) {
            addCriterion("resource_status =", value, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusNotEqualTo(Integer value) {
            addCriterion("resource_status <>", value, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusGreaterThan(Integer value) {
            addCriterion("resource_status >", value, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("resource_status >=", value, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusLessThan(Integer value) {
            addCriterion("resource_status <", value, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusLessThanOrEqualTo(Integer value) {
            addCriterion("resource_status <=", value, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusIn(List<Integer> values) {
            addCriterion("resource_status in", values, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusNotIn(List<Integer> values) {
            addCriterion("resource_status not in", values, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusBetween(Integer value1, Integer value2) {
            addCriterion("resource_status between", value1, value2, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("resource_status not between", value1, value2, "resource_status");
            return (Criteria) this;
        }

        public Criteria andResource_nameLikeInsensitive(String value) {
            addCriterion("upper(resource_name) like", value.toUpperCase(), "resource_name");
            return (Criteria) this;
        }

        public Criteria andResource_descLikeInsensitive(String value) {
            addCriterion("upper(resource_desc) like", value.toUpperCase(), "resource_desc");
            return (Criteria) this;
        }

        public Criteria andResource_typeLikeInsensitive(String value) {
            addCriterion("upper(resource_type) like", value.toUpperCase(), "resource_type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}