package com.rillsoft.stackpoadmin.domain;

import java.io.Serializable;

public class Resource implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_resource.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_resource.resource_name
     *
     * @mbg.generated
     */
    private String resource_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_resource.resource_desc
     *
     * @mbg.generated
     */
    private String resource_desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_resource.resource_type
     *
     * @mbg.generated
     */
    private String resource_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_resource.resource_status
     *
     * @mbg.generated
     */
    private Integer resource_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public Resource(Integer id, String resource_name, String resource_desc, String resource_type, Integer resource_status) {
        this.id = id;
        this.resource_name = resource_name;
        this.resource_desc = resource_desc;
        this.resource_type = resource_type;
        this.resource_status = resource_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    public Resource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_resource.id
     *
     * @return the value of tbl_auth_resource.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_resource.id
     *
     * @param id the value for tbl_auth_resource.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_resource.resource_name
     *
     * @return the value of tbl_auth_resource.resource_name
     *
     * @mbg.generated
     */
    public String getResource_name() {
        return resource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_resource.resource_name
     *
     * @param resource_name the value for tbl_auth_resource.resource_name
     *
     * @mbg.generated
     */
    public void setResource_name(String resource_name) {
        this.resource_name = resource_name == null ? null : resource_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_resource.resource_desc
     *
     * @return the value of tbl_auth_resource.resource_desc
     *
     * @mbg.generated
     */
    public String getResource_desc() {
        return resource_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_resource.resource_desc
     *
     * @param resource_desc the value for tbl_auth_resource.resource_desc
     *
     * @mbg.generated
     */
    public void setResource_desc(String resource_desc) {
        this.resource_desc = resource_desc == null ? null : resource_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_resource.resource_type
     *
     * @return the value of tbl_auth_resource.resource_type
     *
     * @mbg.generated
     */
    public String getResource_type() {
        return resource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_resource.resource_type
     *
     * @param resource_type the value for tbl_auth_resource.resource_type
     *
     * @mbg.generated
     */
    public void setResource_type(String resource_type) {
        this.resource_type = resource_type == null ? null : resource_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_resource.resource_status
     *
     * @return the value of tbl_auth_resource.resource_status
     *
     * @mbg.generated
     */
    public Integer getResource_status() {
        return resource_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_resource.resource_status
     *
     * @param resource_status the value for tbl_auth_resource.resource_status
     *
     * @mbg.generated
     */
    public void setResource_status(Integer resource_status) {
        this.resource_status = resource_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Resource other = (Resource) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getResource_name() == null ? other.getResource_name() == null : this.getResource_name().equals(other.getResource_name()))
            && (this.getResource_desc() == null ? other.getResource_desc() == null : this.getResource_desc().equals(other.getResource_desc()))
            && (this.getResource_type() == null ? other.getResource_type() == null : this.getResource_type().equals(other.getResource_type()))
            && (this.getResource_status() == null ? other.getResource_status() == null : this.getResource_status().equals(other.getResource_status()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getResource_name() == null) ? 0 : getResource_name().hashCode());
        result = prime * result + ((getResource_desc() == null) ? 0 : getResource_desc().hashCode());
        result = prime * result + ((getResource_type() == null) ? 0 : getResource_type().hashCode());
        result = prime * result + ((getResource_status() == null) ? 0 : getResource_status().hashCode());
        return result;
    }
}