package com.rillsoft.stackpoadmin.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andFullnameIsNull() {
            addCriterion("fullname is null");
            return (Criteria) this;
        }

        public Criteria andFullnameIsNotNull() {
            addCriterion("fullname is not null");
            return (Criteria) this;
        }

        public Criteria andFullnameEqualTo(String value) {
            addCriterion("fullname =", value, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameNotEqualTo(String value) {
            addCriterion("fullname <>", value, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameGreaterThan(String value) {
            addCriterion("fullname >", value, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameGreaterThanOrEqualTo(String value) {
            addCriterion("fullname >=", value, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameLessThan(String value) {
            addCriterion("fullname <", value, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameLessThanOrEqualTo(String value) {
            addCriterion("fullname <=", value, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameLike(String value) {
            addCriterion("fullname like", value, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameNotLike(String value) {
            addCriterion("fullname not like", value, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameIn(List<String> values) {
            addCriterion("fullname in", values, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameNotIn(List<String> values) {
            addCriterion("fullname not in", values, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameBetween(String value1, String value2) {
            addCriterion("fullname between", value1, value2, "fullname");
            return (Criteria) this;
        }

        public Criteria andFullnameNotBetween(String value1, String value2) {
            addCriterion("fullname not between", value1, value2, "fullname");
            return (Criteria) this;
        }

        public Criteria andUser_emailIsNull() {
            addCriterion("user_email is null");
            return (Criteria) this;
        }

        public Criteria andUser_emailIsNotNull() {
            addCriterion("user_email is not null");
            return (Criteria) this;
        }

        public Criteria andUser_emailEqualTo(String value) {
            addCriterion("user_email =", value, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailNotEqualTo(String value) {
            addCriterion("user_email <>", value, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailGreaterThan(String value) {
            addCriterion("user_email >", value, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailGreaterThanOrEqualTo(String value) {
            addCriterion("user_email >=", value, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailLessThan(String value) {
            addCriterion("user_email <", value, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailLessThanOrEqualTo(String value) {
            addCriterion("user_email <=", value, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailLike(String value) {
            addCriterion("user_email like", value, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailNotLike(String value) {
            addCriterion("user_email not like", value, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailIn(List<String> values) {
            addCriterion("user_email in", values, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailNotIn(List<String> values) {
            addCriterion("user_email not in", values, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailBetween(String value1, String value2) {
            addCriterion("user_email between", value1, value2, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_emailNotBetween(String value1, String value2) {
            addCriterion("user_email not between", value1, value2, "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_phoneIsNull() {
            addCriterion("user_phone is null");
            return (Criteria) this;
        }

        public Criteria andUser_phoneIsNotNull() {
            addCriterion("user_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUser_phoneEqualTo(String value) {
            addCriterion("user_phone =", value, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneNotEqualTo(String value) {
            addCriterion("user_phone <>", value, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneGreaterThan(String value) {
            addCriterion("user_phone >", value, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_phone >=", value, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneLessThan(String value) {
            addCriterion("user_phone <", value, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneLessThanOrEqualTo(String value) {
            addCriterion("user_phone <=", value, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneLike(String value) {
            addCriterion("user_phone like", value, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneNotLike(String value) {
            addCriterion("user_phone not like", value, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneIn(List<String> values) {
            addCriterion("user_phone in", values, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneNotIn(List<String> values) {
            addCriterion("user_phone not in", values, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneBetween(String value1, String value2) {
            addCriterion("user_phone between", value1, value2, "user_phone");
            return (Criteria) this;
        }

        public Criteria andUser_phoneNotBetween(String value1, String value2) {
            addCriterion("user_phone not between", value1, value2, "user_phone");
            return (Criteria) this;
        }

        public Criteria andLast_loginIsNull() {
            addCriterion("last_login is null");
            return (Criteria) this;
        }

        public Criteria andLast_loginIsNotNull() {
            addCriterion("last_login is not null");
            return (Criteria) this;
        }

        public Criteria andLast_loginEqualTo(Date value) {
            addCriterion("last_login =", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginNotEqualTo(Date value) {
            addCriterion("last_login <>", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginGreaterThan(Date value) {
            addCriterion("last_login >", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login >=", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginLessThan(Date value) {
            addCriterion("last_login <", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginLessThanOrEqualTo(Date value) {
            addCriterion("last_login <=", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginIn(List<Date> values) {
            addCriterion("last_login in", values, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginNotIn(List<Date> values) {
            addCriterion("last_login not in", values, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginBetween(Date value1, Date value2) {
            addCriterion("last_login between", value1, value2, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginNotBetween(Date value1, Date value2) {
            addCriterion("last_login not between", value1, value2, "last_login");
            return (Criteria) this;
        }

        public Criteria andDate_joinedIsNull() {
            addCriterion("date_joined is null");
            return (Criteria) this;
        }

        public Criteria andDate_joinedIsNotNull() {
            addCriterion("date_joined is not null");
            return (Criteria) this;
        }

        public Criteria andDate_joinedEqualTo(Date value) {
            addCriterion("date_joined =", value, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedNotEqualTo(Date value) {
            addCriterion("date_joined <>", value, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedGreaterThan(Date value) {
            addCriterion("date_joined >", value, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_joined >=", value, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedLessThan(Date value) {
            addCriterion("date_joined <", value, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedLessThanOrEqualTo(Date value) {
            addCriterion("date_joined <=", value, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedIn(List<Date> values) {
            addCriterion("date_joined in", values, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedNotIn(List<Date> values) {
            addCriterion("date_joined not in", values, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedBetween(Date value1, Date value2) {
            addCriterion("date_joined between", value1, value2, "date_joined");
            return (Criteria) this;
        }

        public Criteria andDate_joinedNotBetween(Date value1, Date value2) {
            addCriterion("date_joined not between", value1, value2, "date_joined");
            return (Criteria) this;
        }

        public Criteria andUser_statusIsNull() {
            addCriterion("user_status is null");
            return (Criteria) this;
        }

        public Criteria andUser_statusIsNotNull() {
            addCriterion("user_status is not null");
            return (Criteria) this;
        }

        public Criteria andUser_statusEqualTo(Integer value) {
            addCriterion("user_status =", value, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusNotEqualTo(Integer value) {
            addCriterion("user_status <>", value, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusGreaterThan(Integer value) {
            addCriterion("user_status >", value, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_status >=", value, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusLessThan(Integer value) {
            addCriterion("user_status <", value, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusLessThanOrEqualTo(Integer value) {
            addCriterion("user_status <=", value, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusIn(List<Integer> values) {
            addCriterion("user_status in", values, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusNotIn(List<Integer> values) {
            addCriterion("user_status not in", values, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusBetween(Integer value1, Integer value2) {
            addCriterion("user_status between", value1, value2, "user_status");
            return (Criteria) this;
        }

        public Criteria andUser_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("user_status not between", value1, value2, "user_status");
            return (Criteria) this;
        }

        public Criteria andUsernameLikeInsensitive(String value) {
            addCriterion("upper(username) like", value.toUpperCase(), "username");
            return (Criteria) this;
        }

        public Criteria andPasswordLikeInsensitive(String value) {
            addCriterion("upper(password) like", value.toUpperCase(), "password");
            return (Criteria) this;
        }

        public Criteria andFullnameLikeInsensitive(String value) {
            addCriterion("upper(fullname) like", value.toUpperCase(), "fullname");
            return (Criteria) this;
        }

        public Criteria andUser_emailLikeInsensitive(String value) {
            addCriterion("upper(user_email) like", value.toUpperCase(), "user_email");
            return (Criteria) this;
        }

        public Criteria andUser_phoneLikeInsensitive(String value) {
            addCriterion("upper(user_phone) like", value.toUpperCase(), "user_phone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_auth_users
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_auth_users
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}