package com.rillsoft.stackpoadmin.mapper;

import com.rillsoft.stackpoadmin.domain.Resource;
import com.rillsoft.stackpoadmin.domain.ResourceExample;
import com.rillsoft.stackpoadmin.domain.Role;

import java.util.List;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    long countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    Resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Resource record);
    
    // added by Crane Zhou on 12.02.2018
    List<Resource> selectByResourceName(String strResourcename);

//    Resource selectByResourcename(String strResourcename);

    List<Resource> selectAll();
    
//    List<Resource> selectResourceByPage();
}